4bujak-4bujak/backend

- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
- src/main/java/com/example/sabujak/reservation/dto/request/ReservationRequestDto.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
- src/main/java/com/example/sabujak/reservation/entity/Reservation.java
- src/main/java/com/example/sabujak/reservation/repository/MemberReservationRepository.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryCustom.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/space/dto/SpaceType.java
- src/main/java/com/example/sabujak/space/repository/meetingroom/MeetingRoomRepositoryImpl.java
#71 에 관한 PR
마지막 task 빼고 완료
- Change 1
- 9f3a121f3b675841fa09ef2d76a0ab562e79a366, 6eaea5f177dc896884d8969050adf6714e6a9731: 기능 구현에 필요한 구조 변경 및 버그 수정
- Change 2
- e82e5f9948decc14b668fb1b54e2feb5199f5794: 오늘 일정 총 개수 반환하는 API 구현
- Change 3
- 21f0cb172303c784fef3a43364f202970e534b95, 9c8dbeedde104baba0091ef7c01b6e6b9af9549a, b961ce498f4f31a7d96249ae5e6ddd570fbaa983: 당일, 당일포함 30일내 일정 내역 리스트 조회 기능 구현
> feat: 일정(예약) 내역 조회 관련 기능 구현

- src/main/java/com/example/sabujak/privatepost/entity/PrivatePost.java
- src/main/java/com/example/sabujak/privatepost/entity/PrivatePostAnswer.java
컬럼 name 빠진거 작성
- Change 1
- 18ca19016826145883eb7898b8fe8a62da3893ec: 컬럼 name 추가
> fix: #70 enttiy 컬럼명 빠진거 수정

- src/main/java/com/example/sabujak/member/repository/MemberRepositoryCustom.java
- src/main/java/com/example/sabujak/member/repository/MemberRepositoryCustomImpl.java
- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
- src/main/java/com/example/sabujak/reservation/dto/request/ReservationRequestDto.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationResponseDto.java
- src/main/java/com/example/sabujak/reservation/entity/MemberReservation.java
- src/main/java/com/example/sabujak/reservation/exception/ReservationErrorCode.java
- src/main/java/com/example/sabujak/reservation/repository/MemberReservationRepository.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryCustom.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/space/controller/SpaceController.java
- src/main/java/com/example/sabujak/space/dto/response/MeetingRoomResponseDto.java
- src/main/java/com/example/sabujak/space/repository/meetingroom/MeetingRoomRepositoryImpl.java
- src/main/java/com/example/sabujak/space/service/SpaceService.java
#61 에 관한 PR
- Change 1
- 3a280284e729af564c43c459493fe38399dce03f ~ d0941880ac8eb39ae28ae443d1627d51fc8d4b69: 미팅룸 예약 API 구현
- Change 2
- 40c3b74a71157f90f6422b9cb8ecc7adead8f6c1, 1b9bdb75b021e007523946d130d34efd63ab7ae6: 미팅룸 예약 취소 API 구현
> feat: 미팅룸 예약 관련 기능 구현

- src/main/java/com/example/sabujak/branch/controller/BranchController.java
- src/main/java/com/example/sabujak/branch/dto/response/BranchDistanceResponseDto.java
- src/main/java/com/example/sabujak/branch/service/BranchService.java
- src/main/java/com/example/sabujak/image/service/ImageService.java
- src/main/java/com/example/sabujak/privatepost/dto/response/PrivatePostResponseDto.java
#85 에 관한 pr
- Change 1
- 3d4723ae159125943b977680868555d8e8268607: 허용 확장자에 svg 추가
- Change 2
- 672cddaa66fd68242080627b55b29d852f5942a3: 일대일 문의 목록에서 지점명 까지 표시
- Change 3
- 4d243303ccd961b43626736c7e29e2ebc575da94: 가까운 지점 조회 관련 dto 추가
- Change 4
- 12c3cd69fd9759eea30398b1ef4035335fa3a227: 관련 로직 service에 추가
- Change 5
- ca54e1bf732644132ee0139fe6794c7412a96e37: controller 에 관련 코드 추가
이 PR을 확인 할 Code Reviewer에게 남길 메세지를 작성하세요
> feat: 지점 조회 관련 api 구현

- src/main/java/com/example/sabujak/branch/controller/BranchController.java
- src/main/java/com/example/sabujak/branch/dto/response/BranchDistanceResponseDto.java
- src/main/java/com/example/sabujak/branch/service/BranchService.java
- src/main/java/com/example/sabujak/image/service/ImageService.java
- src/main/java/com/example/sabujak/privatepost/dto/response/PrivatePostResponseDto.java
메인으로 실수로 바로 merge 해서 올리는 pr
실수한 pr -> #93
> feature -> develop

- src/main/java/com/example/sabujak/member/dto/response/MemberResponseDto.java
- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationProgress.java
- src/main/java/com/example/sabujak/reservation/repository/MemberReservationRepository.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepository.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryCustom.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/space/repository/meetingroom/MeetingRoomRepositoryImpl.java
#71 관련 PR
- Change 1
- 09ba09a7486f2d1f4190c7001712f35299333759: 일정 조회에서 23 ~ 01 이런식으로 다음날 까지 넘어가는 일정에 대한 처리 + 현재 시간 이후의 예약만 보여주게 리팩토링
- Change 2
- 21e0ca3390cd9fe5bb5dd1e56020126dd30ee20b: 일정 상세 조회 API 구현
> feat: 예약 조회 관련

- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
hotfix: #71 일정 상세 좌석 번호 실수로 뺀거 추가
> hotfix: #71 일정 상세 좌석 번호 실수로 뺀거 추가

- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
hotfix: #71 일정 상세 좌석 번호 실수로 뺀거 추가2
> hotfix: #71 일정 상세 좌석 번호 실수로 뺀거 추가2

- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
> hotfix: #71 일정 상세 spaceId 추가

- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
hotfix: #71 Delete 메소드 RequestBody -> PathVariable
실수로 RequestBody Pathvariable로 안바꾼거 처리
> hotfix: #71 Delete 메소드 RequestBody -> PathVariable 2

- src/main/java/com/example/sabujak/space/controller/SpaceController.java
- src/main/java/com/example/sabujak/space/dto/SpaceCountResponseDto.java
- src/main/java/com/example/sabujak/space/repository/SpaceRepository.java
- src/main/java/com/example/sabujak/space/repository/SpaceRepositoryCustom.java
- src/main/java/com/example/sabujak/space/repository/SpaceRepositoryImpl.java
- src/main/java/com/example/sabujak/space/repository/meetingroom/MeetingRoomRepository.java
- src/main/java/com/example/sabujak/space/service/SpaceService.java
#112 에 관한 pr
- Change 1
- c15548eade37f7fbf47591e08e1cbc487c6e465b : space repository, querydsl 사용 설정 추가
- Change 2
- ccb7a0511936e239d0562639a8618650600e1ac1: 관련 dto 추가 
- Change 3
- c15548eade37f7fbf47591e08e1cbc487c6e465b: meetingroom type별 개수 반환 로직 추가 
- Change 4
- ba062cb44b5e07f40017e035c7b0960c0e8ca029: service에 관련 로직 추가
- Change 5
- 20748bb029c4e4c8e07a899bd10286965b9fddb2: 컨트롤러에 관련 로직 추가
> feat: 지점별 공간 종류 개수 반환 api 구현

- src/main/java/com/example/sabujak/common/dto/ToastType.java
- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
- src/main/java/com/example/sabujak/reservation/dto/request/ReservationRequestDto.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationResponseDto.java
- src/main/java/com/example/sabujak/reservation/exception/ReservationErrorCode.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryCustom.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/space/controller/SpaceController.java
- src/main/java/com/example/sabujak/space/dto/response/MeetingRoomResponseDto.java
- src/main/java/com/example/sabujak/space/dto/response/RechargingRoomResponseDto.java
- src/main/java/com/example/sabujak/space/exception/meetingroom/SpaceErrorCode.java
- src/main/java/com/example/sabujak/space/repository/RechargingRoomRepository.java
- src/main/java/com/example/sabujak/space/service/SpaceService.java
#105 에 관한 PR
- Change 1
- 6103d609db66d427147ef8bd78a621bec991b64f: 리차징룸 리스트 API
- Change 2
- a1dcf61055010bbd2639c78462e420989d1ca3cd: 리차징룸 예약 API
- Change 3
- b825d1064e5aa2ec7b39847aff44545fbcc57b99: 리차징룸 중복 검증 API
그 외 자잘한 rename 및 refactoring
> feat: 리차징룸 예약 관련 기능 구현

- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/space/service/SpaceService.java
#108 에 관한 PR
- Change 1
- 71641d8b1d0cc09c94f17f0d7c939dd746e5fcda, a5d4995fddba278de29b9c35560296a800f93105: 리차징룸 당일만 예약할 수 있게 변경한 후 예약 취소 기능 구현
> feat: 리차징룸 예약 취소 기능 구현

- src/main/java/com/example/sabujak/privatepost/dto/response/PrivatePostResponseDto.java
#130 에 관한 pr
- Change 1
- 097c75a7c86eb672a423febb69f5b2c8409e2bf6 : dto에 답변 내용까지 추가
> feat: #130 일대일 문의 전체 조회시 답변까지 반환

- src/main/java/com/example/sabujak/privatepost/dto/response/PrivatePostResponseDto.java
부자연 스러운 response 이름 수정
- Change 1
- ada1534d6d46bbf9dc7df128dd85c96e851e76ac: 부자연 스러운 파라미터 명 수정
> refatcor: #130 파라미터 명 수정

- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/space/service/SpaceService.java
#135 에 관한 PR
1,2,3 번 버그 해결한 것으로 보임 그리고 해당 버그로 인한 문제 때문에 생긴 버그일 수 있어
일단 지금 버그 수정사항 배포 후 재테스트 예정
- Change 1
- 0f634ecadf8f4192df68a38a65eab549ac932b6f: 첫번째 버그 해결
- Change 2
- 0a72b80443302111ba2aeced58258d16c298d25d: 두번째 버그 해결
- Change 3
- 3b32bc5155e32837a311094759e206c994cb20f3: 세번째 버그 해결
> bug: 1차 테스트 예약 관련 버그 수정

- src/main/java/com/example/sabujak/space/service/SpaceService.java
#135 에 관한 PR
세번째 버그에서 고쳐야할 부분 더 수정
> bug: #135 세번째 버그 해결2

- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/space/service/SpaceService.java
> #139 Develop -> Main

- src/main/java/com/example/sabujak/member/repository/MemberRepositoryCustomImpl.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/space/repository/meetingroom/MeetingRoomRepositoryImpl.java
#135 에 관한 PR
- Change 1
- 910128ed909201d577dcb2b3bc40c98c201fc4fd: 다섯번째 버그 해결
- Change 2
- a734808971a9a2034e344cbb2d3e3e4874772b1d: 여섯번째 버그 해결
- Change 3
-  일곱번째는 프론트에서의 문제로 문제점 찾아 공유 -> 이후 프론트에서 고쳐 배포하면 테스트 예정
> bug: 1차 테스트 예약 관련 버그 수정 2

- src/main/java/com/example/sabujak/image/service/ImageService.java
#150 에 관한 pr
- Change 1
- 9914729d75c666fc7d12b877707d8fd13a0fc1cc: svg 일때 content type 추가 수정
> refactor:  svg 저장 로직 구현

- src/main/java/com/example/sabujak/branch/controller/BranchController.java
- src/main/java/com/example/sabujak/branch/service/BranchService.java
#153 에 관한 pr
- Change 1
- daa28d8ec2dd07a2224f74c796dfeb5db66324c2: 이용중 지점 주변 조회로 로직 변경
> refactor: 사용자 주변 지점조회 에서 이용중 주변 지점 조회로 변경

- src/main/java/com/example/sabujak/branch/controller/BranchController.java
- src/main/java/com/example/sabujak/branch/dto/response/AvailableSpaceCountDto.java
- src/main/java/com/example/sabujak/branch/service/BranchService.java
- src/main/java/com/example/sabujak/reservation/controller/ReservationController.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/space/repository/SpaceRepositoryCustom.java
- src/main/java/com/example/sabujak/space/repository/SpaceRepositoryImpl.java
#153, #154 에 관한 PR
- Change 1
- 1df1f01e890edf42c80eff5355ab8998a68fe044: 지점의 예약 가능한 공간, 총 공간 조회 API 구현
- Change 2
- b9b69dd961d656db410453ba53e55113924e726d: 메인 페이지의 이번 주 일정 API 구현
> feat: 예약 가능 공간 개수, 이번주 일정 기능 구현

- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
#135 의 일곱번째 버그 해결
- Change 1
- e342b962462b70c38fb97e4af3e2b860f39bfd2c: 일곱번째 버그 해결
> bug: #135 일곱번째 버그 해결

- src/main/java/com/example/sabujak/member/service/MemberService.java
#168 에서 작업한 내용 버그 수정
- Change 1
- a59dd4d114de92ac108e826dbdecb04f1cb8e165: 잘못된 로직 수정
> bug: #168 잘못된 로직 수정

- src/main/java/com/example/sabujak/member/entity/Member.java
#168 에서 생긴 버그 수정
- Change 1
- 07c6c91a75be56789c7c665c8086b9428e21683d: 멤버의 기본 시간값 주입
> refactor: #168 memberModalIgnoredTime 이 null 로 들어가는 현상 수정

- src/main/java/com/example/sabujak/member/repository/MemberRepositoryCustomImpl.java
- src/main/java/com/example/sabujak/reservation/dto/response/ReservationHistoryResponse.java
- src/main/java/com/example/sabujak/reservation/repository/MemberReservationRepository.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryCustom.java
- src/main/java/com/example/sabujak/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/com/example/sabujak/reservation/service/ReservationService.java
- src/main/java/com/example/sabujak/security/service/AuthService.java
> develop -> main
